### ISSUE TITLE
Multiple downloads in separate thread race condition

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-third-party#4]
There is race condition happening when two download are happening at the same time - they both try to create the download folder and they fail.

https://github.com/ynput/ayon-third-party/blob/d9c3be4762dd98e971c56fc84aebd0be4024d1a8/client/ayon_third_party/utils.py#L59-L64

It`os.makedirs` is probably just missing `exist_ok=True`

**Comment by iLLiCiTiT** [comment]
Already resolved.
